/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pin/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Pin */
        post: operations["verify_pin_api_v1_auth_pin_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Pin */
        put: operations["set_pin_api_v1_auth_pin_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_v1_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_v1_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Category */
        patch: operations["patch_category_api_v1_categories__category_id__patch"];
        trace?: never;
    };
    "/api/v1/payment-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Payment Methods */
        get: operations["list_payment_methods_api_v1_payment_methods_get"];
        put?: never;
        /** Create Payment Method */
        post: operations["create_payment_method_api_v1_payment_methods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Budget */
        get: operations["current_budget_api_v1_budgets_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Budget */
        post: operations["create_budget_api_v1_budgets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets/{budget_id}/lines/{line_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Budget Line */
        patch: operations["patch_budget_line_api_v1_budgets__budget_id__lines__line_id__patch"];
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Expenses */
        get: operations["list_expenses_api_v1_expenses_get"];
        put?: never;
        /** Create Expense */
        post: operations["create_expense_api_v1_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent */
        get: operations["recent_api_v1_expenses_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Description Suggestions */
        get: operations["description_suggestions_api_v1_expenses_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Expense */
        delete: operations["delete_expense_api_v1_expenses__expense_id__delete"];
        options?: never;
        head?: never;
        /** Patch Expense */
        patch: operations["patch_expense_api_v1_expenses__expense_id__patch"];
        trace?: never;
    };
    "/api/v1/income-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_income_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_v1_income_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/income-sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_api_v1_income_sources__source_id__patch"];
        trace?: never;
    };
    "/api/v1/deductions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deductions */
        get: operations["list_deductions_api_v1_deductions_get"];
        put?: never;
        /** Create Deduction */
        post: operations["create_deduction_api_v1_deductions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deductions/{deduction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Deduction */
        delete: operations["delete_deduction_api_v1_deductions__deduction_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tax/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tax Estimate */
        get: operations["tax_estimate_api_v1_tax_estimate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly */
        get: operations["monthly_api_v1_reports_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/budget-variance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budget Variance */
        get: operations["budget_variance_api_v1_reports_budget_variance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Category Report */
        get: operations["category_report_api_v1_reports_category_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_api_v1_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_api_v1_settings_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BreakdownLineOut */
        BreakdownLineOut: {
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /** Amount */
            amount: number;
        };
        /** BudgetCreate */
        BudgetCreate: {
            /** Period Start */
            period_start?: string | null;
            /** Template */
            template?: string | null;
            /**
             * Total Amount
             * @description poisha
             */
            total_amount?: number | null;
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["BudgetLineIn"][];
            /**
             * Apply Rollover
             * @default true
             */
            apply_rollover: boolean;
        };
        /** BudgetLineIn */
        BudgetLineIn: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /**
             * Amount
             * @description poisha
             */
            amount: number;
            /**
             * Rollover Enabled
             * @default false
             */
            rollover_enabled: boolean;
        };
        /** BudgetLineOut */
        BudgetLineOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Category Name En */
            category_name_en: string;
            /** Category Name Bn */
            category_name_bn: string;
            /** Icon */
            icon: string | null;
            /** Amount */
            amount: number;
            /** Rolled Over Amount */
            rolled_over_amount: number;
            /** Spent */
            spent: number;
            /** Available */
            available: number;
            /** Status */
            status: string;
            /** Rollover Enabled */
            rollover_enabled: boolean;
        };
        /** BudgetLinePatch */
        BudgetLinePatch: {
            /** Amount */
            amount?: number | null;
            /** Rollover Enabled */
            rollover_enabled?: boolean | null;
        };
        /** BudgetOut */
        BudgetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Fiscal Year */
            fiscal_year: string;
            /** Method */
            method: string;
            /** Total Amount */
            total_amount: number;
            /** Total Spent */
            total_spent: number;
            /** Lines */
            lines: components["schemas"]["BudgetLineOut"][];
        };
        /** BudgetVarianceOut */
        BudgetVarianceOut: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Lines */
            lines: components["schemas"]["VarianceLine"][];
            /** Total Budgeted */
            total_budgeted: number;
            /** Total Spent */
            total_spent: number;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /** Parent Id */
            parent_id?: string | null;
            /** Name En */
            name_en: string;
            /** Name Bn */
            name_bn: string;
            /** Icon */
            icon?: string | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parent Id */
            parent_id: string | null;
            /** Name En */
            name_en: string;
            /** Name Bn */
            name_bn: string;
            /** Icon */
            icon: string | null;
            /** Sort Order */
            sort_order: number;
            /** Archived */
            archived: boolean;
        };
        /** CategoryPatch */
        CategoryPatch: {
            /** Name En */
            name_en?: string | null;
            /** Name Bn */
            name_bn?: string | null;
            /** Icon */
            icon?: string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Archived */
            archived?: boolean | null;
        };
        /** CategoryReportOut */
        CategoryReportOut: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Total Spent */
            total_spent: number;
            /** By Category */
            by_category: components["schemas"]["CategorySpend"][];
            /** Subcategories */
            subcategories?: components["schemas"]["CategorySpend"][] | null;
        };
        /** CategorySpend */
        CategorySpend: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Name En */
            name_en: string;
            /** Name Bn */
            name_bn: string;
            /** Icon */
            icon?: string | null;
            /** Spent */
            spent: number;
            /** Entries */
            entries: number;
        };
        /** CategoryTreeOut */
        CategoryTreeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parent Id */
            parent_id: string | null;
            /** Name En */
            name_en: string;
            /** Name Bn */
            name_bn: string;
            /** Icon */
            icon: string | null;
            /** Sort Order */
            sort_order: number;
            /** Archived */
            archived: boolean;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["CategoryOut"][];
        };
        /** DailyPoint */
        DailyPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Spent */
            spent: number;
        };
        /** DeductionCreate */
        DeductionCreate: {
            /** Type */
            type: string;
            /**
             * Amount
             * @description poisha, monthly
             */
            amount: number;
        };
        /** DeductionOut */
        DeductionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Amount */
            amount: number;
            /** Frequency */
            frequency: string;
        };
        /** ExpenseCreate */
        ExpenseCreate: {
            /**
             * Client Uuid
             * Format: uuid
             */
            client_uuid: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /**
             * Amount
             * @description poisha
             */
            amount: number;
            /**
             * Currency
             * @default BDT
             */
            currency: string;
            /**
             * Amount Bdt
             * @description poisha; defaults to amount for BDT
             */
            amount_bdt?: number | null;
            /** Description */
            description?: string | null;
            /** Payment Method Id */
            payment_method_id?: string | null;
            /** For Member Id */
            for_member_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ExpenseListOut */
        ExpenseListOut: {
            /** Items */
            items: components["schemas"]["ExpenseOut"][];
            /** Total */
            total: number;
        };
        /** ExpenseOut */
        ExpenseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Category Name En */
            category_name_en: string;
            /** Category Name Bn */
            category_name_bn: string;
            /** Amount */
            amount: number;
            /** Currency */
            currency: string;
            /** Amount Bdt */
            amount_bdt: number;
            /** Description */
            description: string | null;
            /** Payment Method Id */
            payment_method_id: string | null;
            /**
             * Logged By User Id
             * Format: uuid
             */
            logged_by_user_id: string;
            /** For Member Id */
            for_member_id: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Client Uuid
             * Format: uuid
             */
            client_uuid: string;
        };
        /** ExpensePatch */
        ExpensePatch: {
            /** Date */
            date?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Amount */
            amount?: number | null;
            /** Description */
            description?: string | null;
            /** Payment Method Id */
            payment_method_id?: string | null;
            /** For Member Id */
            for_member_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeSourceCreate */
        IncomeSourceCreate: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Currency
             * @default BDT
             */
            currency: string;
            /**
             * Amount
             * @description poisha, in `currency`
             */
            amount: number;
            /** Amount Bdt */
            amount_bdt?: number | null;
            /**
             * Frequency
             * @default monthly
             */
            frequency: string;
            /**
             * Taxable
             * @default true
             */
            taxable: boolean;
            /**
             * Tds At Source
             * @default false
             */
            tds_at_source: boolean;
            /** Tds Amount Monthly */
            tds_amount_monthly?: number | null;
        };
        /** IncomeSourceOut */
        IncomeSourceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Currency */
            currency: string;
            /** Amount */
            amount: number;
            /** Amount Bdt */
            amount_bdt: number;
            /** Frequency */
            frequency: string;
            /** Taxable */
            taxable: boolean;
            /** Tds At Source */
            tds_at_source: boolean;
            /** Tds Amount Monthly */
            tds_amount_monthly: number | null;
            /** Active */
            active: boolean;
        };
        /** IncomeSourcePatch */
        IncomeSourcePatch: {
            /** Name */
            name?: string | null;
            /** Amount */
            amount?: number | null;
            /** Amount Bdt */
            amount_bdt?: number | null;
            /** Frequency */
            frequency?: string | null;
            /** Taxable */
            taxable?: boolean | null;
            /** Tds At Source */
            tds_at_source?: boolean | null;
            /** Tds Amount Monthly */
            tds_amount_monthly?: number | null;
            /** Active */
            active?: boolean | null;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MonthlySummaryOut */
        MonthlySummaryOut: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Fiscal Year */
            fiscal_year: string;
            /** Income */
            income: number;
            /** Total Spent */
            total_spent: number;
            /** Surplus */
            surplus: number;
            /** Entries */
            entries: number;
            /** By Category */
            by_category: components["schemas"]["CategorySpend"][];
            /** Daily */
            daily: components["schemas"]["DailyPoint"][];
        };
        /** PaymentMethodCreate */
        PaymentMethodCreate: {
            /** Name */
            name: string;
            /** Name Bn */
            name_bn?: string | null;
            /** Icon */
            icon?: string | null;
        };
        /** PaymentMethodOut */
        PaymentMethodOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Name Bn */
            name_bn: string | null;
            /** Icon */
            icon: string | null;
            /** Sort Order */
            sort_order: number;
        };
        /** PinSetIn */
        PinSetIn: {
            /** Password */
            password: string;
            /** Pin */
            pin: string;
        };
        /** PinStatusOut */
        PinStatusOut: {
            /** Ok */
            ok: boolean;
        };
        /** PinVerifyIn */
        PinVerifyIn: {
            /** Pin */
            pin: string;
        };
        /**
         * RecentOut
         * @description Powers 'repeat last entry' and the smart quick-add category grid.
         */
        RecentOut: {
            last: components["schemas"]["ExpenseOut"] | null;
            /** Category Ranking */
            category_ranking: string[];
        };
        /** SettingsOut */
        SettingsOut: {
            /**
             * Household Id
             * Format: uuid
             */
            household_id: string;
            /** Household Name */
            household_name: string;
            /** Fiscal Year Start */
            fiscal_year_start: number;
            /** Base Currency */
            base_currency: string;
            /** Locale */
            locale: string;
        };
        /** SettingsPatch */
        SettingsPatch: {
            /** Household Name */
            household_name?: string | null;
            /** Fiscal Year Start */
            fiscal_year_start?: number | null;
            /** Locale */
            locale?: string | null;
        };
        /**
         * SuggestionOut
         * @description A previously used description, ranked by how often and how recently
         *     the household used it. Powers the entry-form suggestion dropdown.
         */
        SuggestionOut: {
            /** Description */
            description: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Count */
            count: number;
            /**
             * Last Used
             * Format: date
             */
            last_used: string;
        };
        /** TaxEstimateOut */
        TaxEstimateOut: {
            /** Fiscal Year */
            fiscal_year: string;
            /** Verified */
            verified: boolean;
            /** Gross Annual */
            gross_annual: number;
            /** Exemption */
            exemption: number;
            /** Taxable Annual */
            taxable_annual: number;
            /** Gross Tax */
            gross_tax: number;
            /** Rebate */
            rebate: number;
            /** Net Tax Annual */
            net_tax_annual: number;
            /** Monthly Tds */
            monthly_tds: number;
            /** Lines */
            lines: components["schemas"]["BreakdownLineOut"][];
            /** Withheld Annual */
            withheld_annual: number;
            /** Remaining Payable Annual */
            remaining_payable_annual: number;
            /** Monthly Withheld */
            monthly_withheld: number;
            /** Monthly Set Aside */
            monthly_set_aside: number;
            /** Monthly Gross */
            monthly_gross: number;
            /** Monthly Deductions */
            monthly_deductions: number;
            /** Monthly Net */
            monthly_net: number;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VarianceLine */
        VarianceLine: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Name En */
            name_en: string;
            /** Name Bn */
            name_bn: string;
            /** Icon */
            icon: string | null;
            /** Budgeted */
            budgeted: number;
            /** Spent */
            spent: number;
            /** Variance */
            variance: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_pin_api_v1_auth_pin_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinVerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_pin_api_v1_auth_pin_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinSetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_categories_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryTreeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_v1_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_category_api_v1_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_payment_methods_api_v1_payment_methods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodOut"][];
                };
            };
        };
    };
    create_payment_method_api_v1_payment_methods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentMethodCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentMethodOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_budget_api_v1_budgets_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
        };
    };
    create_budget_api_v1_budgets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_budget_line_api_v1_budgets__budget_id__lines__line_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetLinePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expenses_api_v1_expenses_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                category_id?: string | null;
                member_id?: string | null;
                payment_method_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_api_v1_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_api_v1_expenses_recent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentOut"];
                };
            };
        };
    };
    description_suggestions_api_v1_expenses_suggestions_get: {
        parameters: {
            query?: {
                category_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_expense_api_v1_expenses__expense_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_expense_api_v1_expenses__expense_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpensePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_income_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeSourceOut"][];
                };
            };
        };
    };
    create_source_api_v1_income_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomeSourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_api_v1_income_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomeSourcePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deductions_api_v1_deductions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeductionOut"][];
                };
            };
        };
    };
    create_deduction_api_v1_deductions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeductionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeductionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deduction_api_v1_deductions__deduction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deduction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tax_estimate_api_v1_tax_estimate_get: {
        parameters: {
            query?: {
                eligible_investment?: number;
                taxpayer_category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxEstimateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_api_v1_reports_monthly_get: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlySummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    budget_variance_api_v1_reports_budget_variance_get: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetVarianceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    category_report_api_v1_reports_category_get: {
        parameters: {
            query: {
                date_from: string;
                date_to: string;
                category_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_api_v1_export_csv_get: {
        parameters: {
            query: {
                date_from: string;
                date_to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_api_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
