"""zakat calculator and eid mode

Revision ID: 00e04b803721
Revises: f96bfd91bd3a
Create Date: 2026-08-31 15:51:26.016951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e04b803721'
down_revision: Union[str, Sequence[str], None] = 'f96bfd91bd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zakat_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nisab_threshold', sa.BigInteger(), nullable=False),
    sa.Column('rate_bps', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'household',
        sa.Column('eid_mode_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household', 'eid_mode_enabled')
    op.drop_table('zakat_config')
    # ### end Alembic commands ###
