"""50-30-20 and zero-based budgeting

Revision ID: 30223ee656b8
Revises: f59e17162cb1
Create Date: 2026-08-31 15:30:43.936306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30223ee656b8'
down_revision: Union[str, Sequence[str], None] = 'f59e17162cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('assignable_amount', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget', 'assignable_amount')
    # ### end Alembic commands ###
