"""income source tds at source

Revision ID: 3369e33e0bf0
Revises: d2cefca92e3c
Create Date: 2026-08-30 13:48:59.808313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3369e33e0bf0'
down_revision: Union[str, Sequence[str], None] = 'd2cefca92e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_source', sa.Column('tds_at_source', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('income_source', sa.Column('tds_amount_monthly', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income_source', 'tds_amount_monthly')
    op.drop_column('income_source', 'tds_at_source')
    # ### end Alembic commands ###
