"""business investment capital in/out and profit withdrawal transactions

Revision ID: 468831985aab
Revises: 5a3e53a72af8
Create Date: 2026-09-02 14:39:21.515401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468831985aab'
down_revision: Union[str, Sequence[str], None] = '5a3e53a72af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investment_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_transaction_investment_id'), 'investment_transaction', ['investment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_transaction_investment_id'), table_name='investment_transaction')
    op.drop_table('investment_transaction')
    # ### end Alembic commands ###
