"""refresh token deferred rotation

Revision ID: 4a6a4964d997
Revises: 7d3b82595719
Create Date: 2026-09-24 12:15:22.346559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6a4964d997'
down_revision: Union[str, Sequence[str], None] = '7d3b82595719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('replaced_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'refresh_token', 'refresh_token', ['replaced_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.drop_column('refresh_token', 'replaced_by_id')
    # ### end Alembic commands ###
