"""link recurring rules to investment contribution schedules

Revision ID: 5a3e53a72af8
Revises: 720e3549b9e5
Create Date: 2026-09-02 12:25:29.589111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3e53a72af8'
down_revision: Union[str, Sequence[str], None] = '720e3549b9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_rule', sa.Column('investment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'recurring_rule', 'investment', ['investment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurring_rule', type_='foreignkey')
    op.drop_column('recurring_rule', 'investment_id')
    # ### end Alembic commands ###
