"""add household month_start_day

Revision ID: 61773561b412
Revises: 9b0791217651
Create Date: 2026-09-27 16:03:12.796870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61773561b412'
down_revision: Union[str, Sequence[str], None] = '9b0791217651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing (populated) household rows to the
    # calendar-month default - required for a NOT NULL column added here.
    op.add_column(
        'household',
        sa.Column('month_start_day', sa.Integer(), server_default=sa.text('1'), nullable=False),
    )
    op.create_check_constraint('ck_household_month_start_day', 'household', 'month_start_day BETWEEN 1 AND 28')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_household_month_start_day', 'household', type_='check')
    op.drop_column('household', 'month_start_day')
    # ### end Alembic commands ###
