"""link expense to loan given when disbursement is logged as spending

Revision ID: 65a9f60c2cac
Revises: dbf7d5edda7c
Create Date: 2026-09-02 15:52:31.394601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a9f60c2cac'
down_revision: Union[str, Sequence[str], None] = 'dbf7d5edda7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('loan_given_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'expense', 'loan_given', ['loan_given_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'loan_given_id')
    # ### end Alembic commands ###
