"""editable income sources and percentage-based provident fund

Revision ID: 720e3549b9e5
Revises: 00e04b803721
Create Date: 2026-09-01 17:31:33.895419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720e3549b9e5'
down_revision: Union[str, Sequence[str], None] = '00e04b803721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deduction', sa.Column('percentage_bps', sa.Integer(), nullable=True))
    op.add_column('deduction', sa.Column('employer_match_bps', sa.Integer(), nullable=True))
    op.alter_column('deduction', 'amount',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deduction', 'amount',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('deduction', 'employer_match_bps')
    op.drop_column('deduction', 'percentage_bps')
    # ### end Alembic commands ###
