"""zakat config per household

Revision ID: 9b0791217651
Revises: 4a6a4964d997
Create Date: 2026-09-24 12:56:24.302387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0791217651'
down_revision: Union[str, Sequence[str], None] = '4a6a4964d997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zakat_config', sa.Column('household_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'zakat_config', ['household_id'])
    op.create_foreign_key(None, 'zakat_config', 'household', ['household_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zakat_config', type_='foreignkey')
    op.drop_constraint(None, 'zakat_config', type_='unique')
    op.drop_column('zakat_config', 'household_id')
    # ### end Alembic commands ###
