"""investments

Revision ID: 9d50475c1ea2
Revises: f0b04abcae34
Create Date: 2026-08-31 14:50:20.428659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d50475c1ea2'
down_revision: Union[str, Sequence[str], None] = 'f0b04abcae34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('instrument_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('rate_bps', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.Column('current_value', sa.BigInteger(), nullable=True),
    sa.Column('rebate_eligible', sa.Boolean(), nullable=False),
    sa.Column('zakatable', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_household_id'), 'investment', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_household_id'), table_name='investment')
    op.drop_table('investment')
    # ### end Alembic commands ###
