"""debt manager

Revision ID: c867d194a928
Revises: 9d50475c1ea2
Create Date: 2026-08-31 14:58:55.540223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c867d194a928'
down_revision: Union[str, Sequence[str], None] = '9d50475c1ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lender', sa.String(length=120), nullable=True),
    sa.Column('debt_type', sa.String(length=20), nullable=False),
    sa.Column('principal', sa.BigInteger(), nullable=False),
    sa.Column('current_balance', sa.BigInteger(), nullable=False),
    sa.Column('interest_rate_bps', sa.Integer(), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=True),
    sa.Column('minimum_payment', sa.BigInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_household_id'), 'debt', ['household_id'], unique=False)
    op.create_table('debt_payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('debt_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('interest_portion', sa.BigInteger(), nullable=False),
    sa.Column('principal_portion', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['debt_id'], ['debt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_payment_debt_id'), 'debt_payment', ['debt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debt_payment_debt_id'), table_name='debt_payment')
    op.drop_table('debt_payment')
    op.drop_index(op.f('ix_debt_household_id'), table_name='debt')
    op.drop_table('debt')
    # ### end Alembic commands ###
