"""loans given module

Revision ID: dbf7d5edda7c
Revises: 468831985aab
Create Date: 2026-09-02 15:04:15.452819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf7d5edda7c'
down_revision: Union[str, Sequence[str], None] = '468831985aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_given',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('borrower_name', sa.String(length=120), nullable=False),
    sa.Column('borrower_contact', sa.String(length=120), nullable=True),
    sa.Column('principal', sa.BigInteger(), nullable=False),
    sa.Column('current_balance', sa.BigInteger(), nullable=False),
    sa.Column('interest_rate_bps', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_given_household_id'), 'loan_given', ['household_id'], unique=False)
    op.create_table('loan_given_payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('interest_portion', sa.BigInteger(), nullable=False),
    sa.Column('principal_portion', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_given.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_given_payment_loan_id'), 'loan_given_payment', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_given_payment_loan_id'), table_name='loan_given_payment')
    op.drop_table('loan_given_payment')
    op.drop_index(op.f('ix_loan_given_household_id'), table_name='loan_given')
    op.drop_table('loan_given')
    # ### end Alembic commands ###
