"""net worth

Revision ID: f59e17162cb1
Revises: c867d194a928
Create Date: 2026-08-31 15:04:59.815949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59e17162cb1'
down_revision: Union[str, Sequence[str], None] = 'c867d194a928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_worth_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_assets', sa.BigInteger(), nullable=False),
    sa.Column('total_liabilities', sa.BigInteger(), nullable=False),
    sa.Column('net_worth', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'snapshot_date')
    )
    op.create_index(op.f('ix_net_worth_snapshot_household_id'), 'net_worth_snapshot', ['household_id'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('valued_on', sa.Date(), nullable=False),
    sa.Column('logged_by_user_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_household_id'), 'asset', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_household_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_net_worth_snapshot_household_id'), table_name='net_worth_snapshot')
    op.drop_table('net_worth_snapshot')
    # ### end Alembic commands ###
